global:
  scrape_interval: 15s         # Svakih 15s skenira sve targets

scrape_configs:
  - job_name: 'nightclub_app'  # Ime tvog joba
    scrape_interval: 5s        # Svakih 5s skenira backend
    metrics_path: '/metrics'   # Endpoint u app.py
    static_configs:
      - targets: ['backend:5000']  # Backend kontejner:port
